#!/bin/bash --login

#PBS -l walltime=01:00:00

#PBS -l select=1:ncpus=32

#PBS -N core_diversity_analyses_parallel

#PBS -A d411-training



cd $PBS_O_WORKDIR


# Setting temporary directory

mkdir -p ~/qiime_tmp

export TMPDIR=~/qiime_tmp



# Loading modules

module load miniconda/python2



# Loading virtualenv

echo "loading virtualenv"

# NB qiime1 and not qiimel (number one not letter l)

source activate qiime1



# Core Diversity Analyses
core_diversity_analyses.py \

--recover_from_failure \

-i /lustre/home/d411/alorax1/new/2018_02_smb/16S_SILVA128_otus/otu_table_mc2_w_tax.biom \

-o cda_silva \

-m /lustre/home/d411/alorax1/new/2018_02_smb/2018_map.tsv \

-t /lustre/home/d411/alorax1/new/2018_02_smb/16S_SILVA128_otus/rep_set.tre \

-e 745 \ #this number is the fewest OTU counts obtained in the previous OTU picking step

-a \

-O 16



source deactivate