#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N join_pe_reads
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Loading modules
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Joining Paired End Reads
join_paired_ends.py \
-m SeqPrep \
-f Read1.fastq.gz \
-r Read2.fastq.gz \
-b Index.fastq.gz \
-o join_pe_reads \
-j 150 #optional quality filter applied; specifies minimum required bp overlap required to join pairs

source deactivate
