#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N split_libraries_fastq
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Loading modules
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Demultiplexing of Fastq sequence data
split_libraries_fastq.py \
-i /lustre/home/d411/alorax1/new/2018_02_smb/join_pe_reads/seqprep_assembled.fastq.gz \
-b /lustre/home/d411/alorax1/new/2018_02_smb/join_pe_reads/seqprep_assembled.fastq_barcodes.fastq \
-m /lustre/home/d411/alorax1/new/2018_02_smb/2018_map.tsv \
-o split_libraries \
-q 19 #optional quality filter applied \
--store_qual_scores \
--rev_comp_barcode \
--rev_comp_mapping_barcodes

source deactivate