#!/bin/bash --login

#PBS -l walltime=02:00:00

#PBS -l select=1:ncpus=2

#PBS -N a_top_secret_script

#PBS -A d411-training

cd $PBS_O_WORKDIR


# Setting temporary directory

mkdir -p ~/qiime_tmp

export TMPDIR=~/qiime_tmp




# Loading modules

module load miniconda/python2



# Loading virtualenv

echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)

source activate qiime1



#enter qiime script here



source deactivate
