#!/bin/bash --login
#PBS -l walltime=00:01:00
#PBS -l select=1:ncpus=2
#PBS -N rank_abundance
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Filtering OTU singletons from an OTU table
time filter_otus_from_otu_table.py \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_mc2_w_tax.biom \
-o /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_no_singletons.biom \
-n 2

source deactivate
