#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=32
#PBS -N core_diversity_analyses
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Loading modules
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Core Diversity Analyses
core_diversity_analyses.py \
--recover_from_failure \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_no_singletons.biom \
-o /lustre/home/d411/alorax1/data/2018/120000_core_diversity_analyses_updated_map_v2 \
-m /lustre/home/d411/alorax1/data/2018/updated_2018_map_v2.txt \
-t /lustre/home/d411/alorax1/silva128/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-e 35000 \ #this number is obtained by determining sequence count where curve levels off from alpha_rarefaction.py script
-a \
-O 16

source deactivate
