#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=24
#PBS -N pick_open_ref_otus
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Loading modules
module load miniconda/python2

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Picking Operational Taxonomical Units (OTUs)
pick_open_reference_otus.py \
-i /lustre/home/d411/alorax1/new/2018_02_smb/split_libraries/seqs.fna \
-o 16S_SILVA128_otus \
-r /lustre/home/d411/alorax1/silva128/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta \
-a -O 12 \ #this is for parallelising your jobs

source deactivate
