#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N sourcetracker
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

R --slave --vanilla --args \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_mc2_w_tax.txt \
-m /lustre/home/d411/alorax1/data/2018/updated_2018_map_sourcetracker.txt \
-o /lustre/home/d411/alorax1/data/2018/sourcetracker_out < $SOURCETRACKER_PATH/sourcetracker_for_qiime.r

source deactivate
