#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N summarise_taxa_plots
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Summarise the biom table with the mapping file
summarize_taxa_through_plots.py \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_mc2_w_tax.biom \
-m /lustre/home/d411/alorax1/data/2018/2018_02_smb/2018_map.tsv \
-o /lustre/home/d411/alorax1/data/2018/taxa_summary

source deactivate
