#!/bin/bash --login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=72
#PBS -N jackknifed
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Perform jackknifed UPMGA clustering and building jackknifed Emporer PCoA plots
time jackknifed_beta_diversity.py \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_mc2_w_tax.biom \
-o /lustre/home/d411/alorax1/data/2018/jackknifed \
-e 35000 \
-m /lustre/home/d411/alorax1/data/2018/updated_2018_map_v3.txt \
-t /lustre/home/d411/alorax1/silva128/SILVA_128_QIIME_release/trees/97/97_otus.tre \
-a \
-O 36

source deactivate
