#!/bin/bash --login
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=2
#PBS -N 2d_weighted_all
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Make 2D PCoA Plots
time make_2d_plots.py \
-i /lustre/home/d411/alorax1/data/2018/jackknifed/weighted_unifrac/pcoa \
-m /lustre/home/d411/alorax1/data/2018/updated_2018_map_v3.txt \
-o /lustre/home/d411/alorax1/data/2018/2d/weighted_all

source deactivate
