#!/bin/bash --login
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=2
#PBS -N dissimilarity_uw
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Calculate mean, median and standard deviation from a set of distance matrices
time dissimilarity_mtx_stats.py \
-i /lustre/home/d411/alorax1/data/2018/jackknifed/unweighted_unifrac/rare_dm \
-o /lustre/home/d411/alorax1/data/2018/dissimilarity_uw_unifrac_stats

source deactivate
