#!/bin/bash --login
#PBS -l walltime=00:01:00
#PBS -l select=1:ncpus=2
#PBS -N unweighted_boxplots
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Creating plots comparing distances between sample groupings
make_distance_comparison_plots.py \
-m /lustre/home/d411/alorax1/allyears_map_corrected.txt \
-o /lustre/home/d411/alorax1/data/all_years/distance_comparison_plots/2018/unweighted/box \
-d /lustre/home/d411/alorax1/test/all/cda_open/bdiv_even35000/unweighted_unifrac_dm.txt \
-f Year \
-c "2018" \
-t box \
--save_raw_data \
-n 999

source deactivate
