#!/bin/bash --login
#PBS -l walltime=00:01:00
#PBS -l select=1:ncpus=2
#PBS -N rank_abundance
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Plotting a rank abundance curve from an OTU table
time plot_rank_abundance_graph.py \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_mc2_w_tax.biom \
-s '*' \
-o /lustre/home/d411/alorax1/data/2018/rank_abundance/normal.png \
-f png

source deactivate
