#!/bin/bash --login
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=2
#PBS -N grass_gtest
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Comparing OTU frequencies across sample groups (for grass 2018 dataset)
time group_significance.py \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_no_singletons.biom \
-m /lustre/home/d411/alorax1/data/2018/updated_2018_map_v3.txt \
-c SampleGrass \
-s g_test \
-o /lustre/home/d411/alorax1/data/2018/group_significance_results/2018/gtest_grass.txt

source deactivate
