#!/bin/bash --login
#PBS -l walltime=00:03:00
#PBS -l select=1:ncpus=2
#PBS -N 15
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Make OTU heatmap
time make_otu_heatmap.py \
-i /lustre/home/d411/alorax1/data/2018/new_heatmaps/taxa_summaries/90_core/core_table_90_L2.biom \
-o /lustre/home/d411/alorax1/data/2018/new_heatmaps/90_core.pdf \
-t /lustre/home/d411/alorax1/silva128/SILVA_128_QIIME_release/trees/97/97_otus.tre \
--color_scheme winter

source deactivate
