#!/bin/bash --login
#PBS -l walltime=00:02:00
#PBS -l select=1:ncpus=2
#PBS -N core
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Identifying the core microbiome where core = 50% of samples
time compute_core_microbiome.py \
-i /lustre/home/d411/alorax1/data/2018/otu_open_ref/otu_table_mc2_w_tax.biom \
-o /lustre/home/d411/alorax1/data/2018/core_microbiome

source deactivate
