#!/bin/bash --login
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=2
#PBS -N distance_boxplots
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Plotting within and between distances for SampleMoisture
time make_distance_boxplots.py \
-m /lustre/home/d411/alorax1/data/2018/updated_2018_map_v2.txt \
-o /lustre/home/d411/alorax1/data/2018/distance_boxplots/test \
-d /lustre/home/d411/alorax1/data/2018/try2_35000_cda/bdiv_even35000/unweighted_unifrac_dm.txt \
-f SampleMoisture \
--save_raw_data \
-n 999



source deactivate
