#!/bin/bash --login
#PBS -l walltime=00:03:00
#PBS -l select=1:ncpus=2
#PBS -N validate_map
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Validating the mapping file
time validate_mapping_file.py \
-m /lustre/home/d411/alorax1/data/all_years/allyears_map.txt \
-o /lustre/home/d411/alorax1/data/all_years/validate_mapping_file

source deactivate
