#!/bin/bash --login
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=2
#PBS -N convert_fastq
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Converting qual file to the right format
convert_fastaqual_fastq.py \
-f /lustre/home/d411/alorax1/data/2018/split_libraries_none_19/seqs.fna \
-q /lustre/home/d411/alorax1/data/2018/split_libraries_none_19/seqs.qual \
-o /lustre/home/d411/alorax1/data/2018/converted_fastq

source deactivate
