#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N quality_scores_plot
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Load modules and qiime
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Generating Quality Scores
quality_scores_plot.py \
-q /lustre/home/d411/alorax1/data/2018/split_libraries_none_19/seqs.qual \
-o /lustre/home/d411/alorax1/data/2018/quality_none_histograms

source deactivate
