#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=32
#PBS -N pick_open_ref_otus
#PBS -A d411-training

cd $PBS_O_WORKDIR

# Loading modules
module load miniconda/python2

# Setting temporary directory
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

# Loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1

# Picking Operational Taxonomical Units (OTUs)
pick_open_reference_otus.py \
-i /lustre/home/d411/alorax1/data/2018/split_libraries_none_19/seqs.fna \
-o /lustre/home/d411/alorax1/data/2018/otu_open_ref \
-r /lustre/home/d411/alorax1/silva128/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta \
-a \
-O 16 #this is for parallelising jobs

source deactivate
